CREATE TABLE user
(
    id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login    VARCHAR(31)    NOT NULL UNIQUE,
    passhash VARCHAR(128)   NOT NULL,
    balance  NUMERIC(19, 2) NOT NULL DEFAULT 500.00
);