@host = localhost:8080
@rootRoute = http://{{host}}

###
# @name SignIn
POST {{rootRoute}}/signin
Content-Type: application/json

{
  "login": "ashdf",
  "password": "pass"
}


###
# @name SignUp
POST {{rootRoute}}/signup
Content-Type: application/json

{
  "login": "ashkijhgdf",
  "password": "pass"
}


