@host = localhost:8080
@root = http://{{host}}

###
# @name SignIn
POST {{root}}/signin
Content-Type: application/json

{
  "login": "ashdf",
  "password": "pass"
}


###
# @name SignUp
POST {{root}}/signup
Content-Type: application/json

{
  "login": "ashkijhgdf",
  "password": "pass"
}


