@host = localhost:8080
@root = http://{{host}}/money
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTUzNzk5MDcsInN1YiI6ImFzaGRmIn0.iyw1NVJZdTmgq0_gXAasuvLxkE0U6gPyd4XIZAiaApo


###
# @name GetBalance
GET {{root}}
Authorization: Bearer {{jwt}}


###
# @name SendMoney
POST {{root}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "to": "asdf",
  "amount": 1.0
}