@host = localhost:8080
@rootRoute = http://{{host}}


###
# @name GetBalance
GET {{rootRoute}}/money?id=2


###
# @name SendMoney
POST {{rootRoute}}/money
Content-Type: application/json

{"to": "asdf", "amount": 13.0}