@host = localhost:8080
@root = http://{{host}}/money
// enter token from signin/signup response
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTU1Njg5MTcsInN1YiI6ImFzaGRmIn0.vhkVy_45yJz1MUcaJOTgxqgCtSLSj43WGpvqbCpcKuc


###
# @name GetBalance
GET {{root}}
Authorization: Bearer {{jwt}}


###
# @name SendMoney
POST {{root}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "to": "test_login_2",
  "amount": 1.5
}