@host = localhost:8083
@rootRoute = http://{{host}}

###
# @name GetBalance
GET {{rootRoute}}/money?id=2

###
# @name SignUp
POST {{rootRoute}}/signup
Content-Type: application/json

{"login": "asdf", "password":  "312354"}